#:schema node_modules/wrangler/config-schema.json
name = "travel-app"
compatibility_date = "2026-07-15"

# Points Cloudflare strictly to your compiled front-end user interface
[assets]
directory = "./dist"

[build]
command = "npm run build"
